{"uuid": "528840df-59db-44e6-bff4-032ee756eda4", "children": ["6a2798be-1ea4-47ad-b95c-48b4ee90bec3"], "befores": [{"name": "register_setup", "status": "passed", "start": 1626701994472, "stop": 1626701994472}], "afters": [{"name": "register_setup::0", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: 'F:\\\\BaiduNetdiskWorkspace\\\\api_test_pytest\\\\test_result\\\\test.log'\n", "trace": "  File \"e:\\pycharmprojects\\apptest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"e:\\pycharmprojects\\apptest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"F:\\BaiduNetdiskWorkspace\\api_test_pytest\\test_case\\conftest.py\", line 35, in register_setup\n    my_log.info(\"一条测试用例执行完毕\")\n  File \"F:\\BaiduNetdiskWorkspace\\api_test_pytest\\common\\my_log.py\", line 44, in info\n    self.my_log('INFO', msg)\n  File \"F:\\BaiduNetdiskWorkspace\\api_test_pytest\\common\\my_log.py\", line 18, in my_log\n    fh = logging.FileHandler(project_path.log_path, encoding='utf-8')  # 文件不存在时自动生成\n  File \"E:\\Program Files\\Python38\\lib\\logging\\__init__.py\", line 1143, in __init__\n    StreamHandler.__init__(self, self._open())\n  File \"E:\\Program Files\\Python38\\lib\\logging\\__init__.py\", line 1172, in _open\n    return open(self.baseFilename, self.mode, encoding=self.encoding)\n"}, "start": 1626701994731, "stop": 1626701994733}], "start": 1626701994472, "stop": 1626701994734}