INFO     api_log:my_log.py:29 -----正在测试login模块里面第4条测试用例：输入错误的密码,
INFO     api_log:my_log.py:29 测试数据是：{'mobilephone': '18300070752', 'pwd': '1234567'}
INFO     api_log:my_log.py:29 实际结果是:{'status': 0, 'code': '20111', 'data': None, 'msg': '用户名或密码错误'}
INFO     api_log:my_log.py:29 一条测试用例执行完毕